### ISSUE TITLE
Incompatibility with Rimpedia and Vanilla Animal Overhaul Reloaded

### ISSUE THREAD

**Issue by Ano-Nymus** [juanosarg/VanillaAnimalsExpanded-BorealForest#1]
### Description

The mod causes an issue when used together with both rimpedia and vanilla animals overhaul.
I do not know why, but only when running all three mods at the same time (any load order).

### Mods

https://steamcommunity.com/sharedfiles/filedetails/?id=2145524536
https://steamcommunity.com/sharedfiles/filedetails/?id=1588681499

### Error Report

Failed to find any textures at Things/Pawn/Animal/BlackBear/BlackBearPack while constructing Multi(initPath=Things/Pawn/Animal/BlackBear/BlackBearPack, color=RGBA(1.000, 1.000, 1.000, 1.000), colorTwo=RGBA(1.000, 1.000, 1.000, 1.000))
Verse.Log:Error(String, Boolean)
Verse.Graphic_Multi:Init(GraphicRequest)
Verse.GraphicDatabase:GetInner(GraphicRequest)
Verse.GraphicDatabase:Get(String)
Rimpedia.StageAnimalGraphic:.ctor(PawnKindDef, PawnKindLifeStage, Boolean)
Rimpedia.RimpediaAnimalThing:resolveGraphics(ThingDef)
Rimpedia.RimpediaAnimalThing:.ctor(ThingDef)
Rimpedia.ThingList:.ctor()
Rimpedia.Cache:.cctor()
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(IntPtr)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(RuntimeTypeHandle)
Verse.StaticConstructorOnStartupUtility:CallAll()
Verse.<>c:<DoPlayLoad>b__4_2()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent()
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Update()
Verse.Root_Entry:Update()

Object reference not set to an instance of an object
Verse.Log:Error(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
Rimpedia.ThingList:.ctor()
Rimpedia.Cache:.cctor()
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(IntPtr)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(RuntimeTypeHandle)
Verse.StaticConstructorOnStartupUtility:CallAll()
Verse.<>c:<DoPlayLoad>b__4_2()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent()
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Update()
Verse.Root_Entry:Update()

at Rimpedia.AnimalGraphic..ctor (Verse.Graphic g, System.Single scale) [0x00039] in <dd9cdfd213db4d76bf6f4f1e44d85df2>:0
at Rimpedia.RimpediaAnimalThing+StageAnimalGraphic..ctor (Verse.PawnKindDef pawn, Verse.PawnKindLifeStage stage, System.Boolean isPack) [0x000a0] in <dd9cdfd213db4d76bf6f4f1e44d85df2>:0
at Rimpedia.RimpediaAnimalThing.resolveGraphics (Verse.ThingDef td) [0x00130] in <dd9cdfd213db4d76bf6f4f1e44d85df2>:0
at Rimpedia.RimpediaAnimalThing..ctor (Verse.ThingDef td) [0x00025] in <dd9cdfd213db4d76bf6f4f1e44d85df2>:0
at Rimpedia.Cache+ThingList..ctor () [0x000d5] in <dd9cdfd213db4d76bf6f4f1e44d85df2>:0
Verse.Log:Error(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
Rimpedia.ThingList:.ctor()
Rimpedia.Cache:.cctor()
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(IntPtr)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(RuntimeTypeHandle)
Verse.StaticConstructorOnStartupUtility:CallAll()
Verse.<>c:<DoPlayLoad>b__4_2()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent()
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Update()
Verse.Root_Entry:Update()

**Comment by juanosarg** [comment]
This is caused by vanilla animals overhaul making the bear a pack animal (which is a reeeeaaaaally stupid thing). Since this is added to the bear base, any animal inheriting from it such as the black bear will be a pack animal, and we obviously didn't provide pack graphics for it.

**Comment by Ano-Nymus** [comment]
Thanks for the quick answer. I guess this should be changed by Animal Overhaul - some questions though: 
Why does this bug only appear when also using Rimpedia?  
And why does it not appear with any other animal/bear?

**Comment by Ano-Nymus** [comment]
**Quick Note:** 

I replaced Vanilla Animals Overhaul with More Pack Animals, which caused the same error to appear as well.
Replacing Vanilla Animals Expanded with Synthetic Animals causes similar errors, this time for two other animals.

Closing this issue, since this is obviously the fault of Pack Animal changes, nor of your mod.
